### Register
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "username": "alfonsoxd",
  "email": "alfonsoxc@gmail.com",
  "password": "1234565",
  "role": "requester"
}

> {%
    client.global.set("username", response.body.data.username);
    client.global.set("password", response.body.data.email);
%}

###

### Register
GET {{baseUrl}}/users?limit=2&page=1
Content-Type: application/json
